version: 0.0
os: linux
files:
  - source: /package.zip
    destination: /var/www/
# For deployments to Amazon Linux, Ubuntu Server, or RHEL instances,
#   you can specify a "permissions"
#   section here that describes special permissions to apply to the files
#   in the "files" section as they are being copied over to
#   the Amazon EC2 instance.
# permissions:
#   - object:
#     pattern:
#     except:
#     owner:
#     group:
#     mode:
#     acls:
#       -
#     context:
#       user:
#       type:
#       range:
#     type:
#       -
# If you are not running any commands on the Amazon EC2 instance, then remove
#   the "hooks" section altogether. A blank or incomplete "hooks" section
#   may cause associated deployments to fail.
hooks:
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
    runas: root
  AfterInstall:
    - location: scripts/build
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start
      timeout: 300
      runas: root